version: "3.8"
services: 
    bot:
        image: demonoverlord:latest # the image will be on the same device but pushed and built on and from other machines
        ports:
            - "443:443"
        restart: always
        env_file:
            - ~/bot/.env
        environment:
            DISCORD_MAIN_TOKEN:
            DISCORD_TESTBOT_TOKEN:
            TENOR_TOKEN:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
        depends_on:
            - "postgres"
    postgres:
        image: postgres:13.0
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - ~/bot/.env
        environment: 
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB: bot_core
        volumes: 
            - ~/bot/database-data:/var/lib/postgresql/data
        

    
